# Generated by Django 3.1.3 on 2021-12-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20211207_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_answer',
            new_name='is_correct',
        ),
    ]
